version: "3.3"
services: 
  node:
    image: pauulosergio/loja_fumo:latest
    container_name: express-api
    ports:
      - "8080:8080"
      - "5555:5555"
    networks:
      - docker-service
    restart: on-failure

  mariadb:
    image: mariadb:latest
    container_name: docker-mariadb
    ports:
      - "3306:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: "password"
    networks:
      - docker-service
    volumes:
      - maria-data:/data/db
    healthcheck:
      test: ['CMD', '/usr/local/bin/healthcheck.sh', '--connect']
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  docker-service:
    driver: bridge

volumes:
  maria-data:
    driver: local
